package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/pelletier/go-toml/v2"
)

type TomlCommand struct {
	Name        string   `toml:"name"`
	Aliases     []string `toml:"aliases"`
	Level       string   `toml:"level"`
	Standalone  []string `toml:"standalone"`
	Valued      []string `toml:"valued"`
	BareFlags   []string `toml:"bare_flags"`
	SubCommands []TomlSubCommand `toml:"sub"`
}

type TomlSubCommand struct {
	Name        string   `toml:"name"`
	Level       string   `toml:"level"`
	Bare        *bool    `toml:"bare"`
	Standalone  []string `toml:"standalone"`
	Valued      []string `toml:"valued"`
	AllowAll    *bool    `toml:"allow_all"`
	Delegate    string   `toml:"delegate"`
	SubSub      []TomlSubCommand `toml:"sub"`
}

func main() {
	root := "_ref-safe-chains/commands"
	outPath := "internal/builtin/generated_commands.go"

	byCategory := make(map[string][]string) // category → commands

	filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || !strings.HasSuffix(info.Name(), ".toml") {
			return nil
		}
		if info.Name() == "SAMPLE.toml" {
			return nil
		}

		// Get category from directory path
		rel, _ := filepath.Rel(root, filepath.Dir(path))
		if rel == "." {
			rel = "root"
		}
		category := rel

		data, err := os.ReadFile(path)
		if err != nil {
			return nil
		}

		var doc struct {
			Commands []TomlCommand `toml:"command"`
		}
		if err := toml.Unmarshal(data, &doc); err != nil {
			fmt.Fprintf(os.Stderr, "  skip %s: %v\n", info.Name(), err)
			return nil
		}

		for _, cmd := range doc.Commands {
			names := append([]string{cmd.Name}, cmd.Aliases...)
			if cmd.Name == "" {
				continue
			}

			for _, name := range names {
				// Skip npm scoped packages and non-standard command names
				if strings.HasPrefix(name, "@") || strings.Contains(name, "/") || strings.Contains(name, "\\") {
					continue
				}
				// Skip pure operators
				if name == ":" || name == "." {
					continue
				}

				hasSub := len(cmd.SubCommands) > 0

				if hasSub {
					// Base command: allow for --help/--version
					byCategory[category] = append(byCategory[category], name)

					for _, sub := range cmd.SubCommands {
						fullName := name + " " + sub.Name

						// Skip delegate commands (they hand off to another tool)
						if sub.Delegate != "" {
							continue
						}

						// AllowAll → allow the subcommand with any args
						if sub.AllowAll != nil && *sub.AllowAll {
							byCategory[category] = append(byCategory[category], fullName+" *")
							continue
						}

						// SafeWrite → ask, otherwise allow
						if sub.Level == "SafeWrite" {
							continue // skip for now, handled by base ask logic
						}

						byCategory[category] = append(byCategory[category], fullName)

						// Handle sub-subcommands
						for _, subsub := range sub.SubSub {
							ssName := fullName + " " + subsub.Name
							byCategory[category] = append(byCategory[category], ssName)
						}
					}
				} else {
					// Flat command (no subcommands)
					isSafe := cmd.Level == "" || cmd.Level == "Inert" || cmd.Level == "SafeRead"
					if isSafe {
						byCategory[category] = append(byCategory[category], name)
					}
				}
			}
		}
		return nil
	})

	// Collect and deduplicate
	allSeen := make(map[string]bool)
	var allCmds []string
	var categories []string
	for cat := range byCategory {
		categories = append(categories, cat)
	}
	sort.Strings(categories)

	for _, cat := range categories {
		cmds := byCategory[cat]
		sort.Strings(cmds)
		for _, c := range cmds {
			if !allSeen[c] {
				allSeen[c] = true
				allCmds = append(allCmds, c)
			}
		}
	}

	// Generate Go code
	var sb strings.Builder
	sb.WriteString("// Code generated by internal/builtin/cmd/convert.go; DO NOT EDIT.\n")
	sb.WriteString("package builtin\n\n")
	sb.WriteString("func generatedAllow() []string {\n")
	sb.WriteString("\treturn []string{\n")
	for _, c := range allCmds {
		sb.WriteString(fmt.Sprintf("\t\t%q,\n", c))
	}
	sb.WriteString("\t}\n")
	sb.WriteString("}\n")

	if err := os.WriteFile(outPath, []byte(sb.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write error: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Written to %s\n", outPath)
	fmt.Printf("  Total patterns: %d\n", len(allCmds))
	fmt.Printf("  Categories:     %d\n", len(categories))
	for _, cat := range categories {
		fmt.Printf("    %-20s %3d\n", cat, len(byCategory[cat]))
	}
}
